workflow updates

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -76,10 +76,16 @@ jobs:
           cargo build --release --target $(arch)-unknown-linux-musl
 
       - name: Link status
-        continue-on-error: true
         run: |
-          ldd target/$(arch)-unknown-linux-musl/release/aperf
-
+          output=$(ldd target/$(arch)-unknown-linux-musl/release/aperf 2>&1)
+          if [[ $output == *"not a dynamic executable"* ]] || [[ $output == *"statically linked"* ]]; then
+            echo "Static executable confirmed"
+            exit 0
+          else
+            echo "Error: Executable is dynamically linked"
+            echo "$output"
+            exit 1
+          fi
       - name: Archive release artifacts
         run: tar -zcvf artifacts.tar.gz -C target/$(arch)-unknown-linux-musl/release aperf
       - name: Upload x86_64 release artifacts
